[package]
name = "todoer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
env_logger = "0.11.3"
ignore = "0.4.22"
log = "0.4.22"
